#ifndef DRA_MIPS_C_SYSCALL_H
#define DRA_MIPS_C_SYSCALL_H

#define SYSCALL_PRINT_INTEGER 1
#define SYSCALL_PRINT_FLOAT 2
#define SYSCALL_PRINT_DOUBLE 3
#define SYSCALL_PRINT_STRING 4

#define SYSCALL_READ_INTEGER 5
#define SYSCALL_READ_FLOAT 6
#define SYSCALL_READ_DOUBLE 7
#define SYSCALL_READ_STRING 8

#define SYSCALL_PRINT_CHARACTER 11
#define SYSCALL_READ_CHARACTER 12

#define SYSCALL_EXIT 10
#define SYSCALL_EXIT2 17

#endif
